### ISSUE TITLE
Could BigDecimal be used for Money?

### ISSUE THREAD

**Issue by flappingeagle** [sofort/sofortlib-java#5]
BigDecimal is recommended best practice for representing monetary values in Java. 
It would be good if sofortlib-java also uses BigDecimal instead of Double in every place where monetary values need to be given.

See: https://stackoverflow.com/questions/285680/representing-monetary-values-in-java
See: https://stackoverflow.com/questions/1359817/using-bigdecimal-to-work-with-currencies

**Comment by FxAlex** [comment]
Yes, it is possible and you should use BigDecimal, Long or better an ISO4217 implementing framework for monetary operations. But sofortlib Client generates an XML code and XML doesn't "knows" any doubles or BigDecimals, but Strings. So it doesn't matter if we convert a double or a BigDecimal value to the defined(by API) "Decimal (8.2)" String - the result (XML) will be the same.

API: https://www.sofort.com/integrationCenter-ger-DE/content/view/full/2513#h5-1-2

**Comment by flappingeagle** [comment]
yes, but currently i have the burden, to convert the bigdecimal to a double at the place where i use the sofort-api. If the sofort-api would also accept bigdecimal it would mean "less code i need to write".

See following example, how i do it now:

<pre>
        final Short scale;
        if (order.getScale() != null) {
            scale = order.getScale();
        } else {
            scale = 2;
        }
        final BigDecimal localizedTotal = order.getTotal().setScale(scale);
        final String amountStr = localizedTotal.toPlainString();
        final Double localizedTotalDouble = new Double(amountStr);

        final PaymentRequest paymentRequest = new PaymentRequest(
                projectId,
                localizedTotalDouble,
                currency,
                purposes,
                consumerProtection);
</pre>

now that i think of it, it may be better that i need to convert the bigdecimal to double myself, because i have more control over the conversion... so i think its ok to leave it as a double.

**Comment by FxAlex** [comment]
do not forget the rounding mode:
<pre>  final BigDecimal localizedTotal = order.getTotal().setScale(scale, <b>RoundingMode.HALF_UP</b>);</pre>

and two followed up lines of code can be reduced to:
<pre>  final double localizedTotalAmount = localizedTotal.doubleValue();</pre>

**Comment by flappingeagle** [comment]
yes thx!
